In [1]:
import pandas as pd


In [2]:
pd.__version__

'2.2.2'

In [4]:
#atributos previsores
X = pd.read_csv('/content/entradas_breast.csv')
X

radius_mean   texture_mean   perimeter_mean   area_mean  \
0           17.99          10.38           122.80      1001.0   
1           20.57          17.77           132.90      1326.0   
2           19.69          21.25           130.00      1203.0   
3           11.42          20.38            77.58       386.1   
4           20.29          14.34           135.10      1297.0   
..            ...            ...              ...         ...   
564         21.56          22.39           142.00      1479.0   
565         20.13          28.25           131.20      1261.0   
566         16.60          28.08           108.30       858.1   
567         20.60          29.33           140.10      1265.0   
568          7.76          24.54            47.92       181.0   

      smoothness_mean   compactness_mean   concavity_mean  \
0             0.11840            0.27760          0.30010   
1             0.08474            0.07864          0.08690   
2             0.10960            0.15990          0.19740   
3             0.14250            0.28390          0.24140   
4             0.10030            0.13280        198.00000   
..                ...                ...              ...   
564         111.00000            0.11590          0.24390   
565           0.09780            0.10340        144.00000   
566           0.08455            0.10230          0.09251   
567           0.11780          277.00000          0.35140   
568           0.05263            0.04362          0.00000   

     concave_points_mean   symmetry_mean   fractal_dimension_mean  ...  \
0                0.14710          0.2419                  0.07871  ...   
1                0.07017          0.1812                  0.05667  ...   
2                0.12790          0.2069                  0.05999  ...   
3                0.10520          0.2597                  0.09744  ...   
4                0.10430          0.1809                  0.05883  ...   
..                   ...             ...                      ...  ...   
564              0.13890          0.1726                  0.05623  ...   
565              0.09791          0.1752                  0.05533  ...   
566              0.05302        159.0000                  0.05648  ...   
567            152.00000          0.2397                  0.07016  ...   
568              0.00000          0.1587                  0.05884  ...   

      radius_worst   texture_worst   perimeter_worst   area_worst  \
0            25.38           17.33            184.60       2019.0   
1            24.99           23.41            158.80       1956.0   
2            23.57           25.53            152.50       1709.0   
3            14.91           26.50             98.87        567.7   
4            22.54           16.67            152.20       1575.0   
..             ...             ...               ...          ...   
564          25.45           26.40            166.10       2027.0   
565          23.69           38.25            155.00       1731.0   
566          18.98           34.12            126.70       1124.0   
567          25.74           39.42            184.60       1821.0   
568        9456.00           30.37             59.16        268.6   

      smoothness_worst   compactness_worst   concavity_worst  \
0              0.16220             0.66560            0.7119   
1              0.12380             0.18660            0.2416   
2              0.14440             0.42450            0.4504   
3              0.20980             0.86630            0.6869   
4              0.13740           205.00000            0.4000   
..                 ...                 ...               ...   
564          141.00000             0.21130            0.4107   
565            0.11660             0.19220            0.3215   
566            0.11390             0.30940            0.3403   
567          165.00000             0.86810            0.9387   
568            0.08996             0.06444            0.0000   

     

In [5]:
#classe
y = pd.read_csv('/content/saidas_breast.csv')
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [6]:
#Divisão da base entre dados de treinamento e dados de teste
from sklearn.model_selection import train_test_split


In [7]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.25)

In [8]:
X_treinamento.shape, y_treinamento.shape

((426, 30), (426, 1))

In [9]:
X_teste.shape, y_teste.shape

((143, 30), (143, 1))

In [10]:
#Montando a estrutura da rede neural
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [11]:
#quantidade de neuronios na camada oculta:
(30+1)/2

15.5

In [24]:
rede_neural = Sequential([
    #camada de entrada:
    tf.keras.layers.InputLayer(shape=(30,)),
    #camada oculta(nesse exemplo, apenas uma):
    tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'),
    #Segunda camada oculta:
    tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'),
    #camada de saída:
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])
#Na camada oculta, o "Dense" significa que a camada oculta está ligada a todos os neurônios da próxima camada
#Units se refere à qtde de neuronios da camada oculta. Para saber a quantidade de neuronios, fazemos a (qtde de atributos previsores + qtd de saídas/2)
#Utilizamos a função relu, pois as outras funções são utilizadas na camada de saída
# A função de ativação da camada de saída será a sigmoide, pois temos um problema de classificação binária

In [25]:
rede_neural.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 16)                  │             496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 16)                  │             272 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
#O valor de 496 parametros é o equivalente a 30 neuronios da camada de entrada * 16 neuronios da camada oculta. O restante são os bias adicionados.
# O valor total de parametros correspondem aos pesos que serão ajustados durante a etapa de treinamento
#Em uma rede neural densa, todos os neurônios de uma camada estão ligados a todos os neurônios da próxima camada

In [27]:
#Criando um otimizador
#Clipvalue: os pesos nunca vão ultrapassar o valor
otimizador = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue=0.5)

In [28]:
#Aqui, estamos escolhendo o algoritmo que vai ser utilizado para o ajuste dos pesos, também definimos o algoritmo que vai ser usado para calcular os erros (loss)
# LER A DOCUMENTAÇÃO
#Em cada uma das epocas, a rede neural vai processar todos os registros
rede_neural.compile(optimizer= 'adam', loss = 'binary_crossentropy', metrics = ['binary_accuracy'])
rede_neural.fit(X_treinamento,y_treinamento, batch_size=10, epochs=100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.5391 - loss: 2.7986
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.6095 - loss: 0.5638
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.6235 - loss: 0.5411
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.6810 - loss: 0.4919
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7075 - loss: 0.4636
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7853 - loss: 0.4195
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7964 - loss: 0.3782
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8101 - loss: 0.4033
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8508 - loss: 0.3727
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8783 - loss: 0.3223
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8656 -

In [31]:
pesos0 = rede_neural.layers[0].get_weights()
pesos0
#pesos aprendidos durante o treinamento

[array([[ 4.25813347e-02, -4.03243583e-03,  2.95952633e-02,
          3.04109361e-02,  3.42622176e-02,  4.07472104e-02,
         -4.06755805e-02, -2.61811882e-01,  4.97626513e-02,
         -6.47042505e-03,  3.22828367e-02,  4.81890216e-02,
          5.33714630e-02, -1.70725007e-02,  2.54800562e-02,
         -1.34788290e-01],
        [ 3.83104756e-02, -5.95747195e-02,  3.07564903e-02,
         -2.47163791e-03, -1.39109075e-01,  3.73013243e-02,
         -1.66597962e-02, -2.34979037e-02,  6.88992664e-02,
         -4.39700969e-02,  4.40594591e-02,  3.00052725e-02,
          2.17493862e-01, -2.91426163e-02, -3.80783416e-02,
         -9.18340385e-02],
        [ 1.60093799e-01, -1.14362752e-02, -3.76939997e-02,
          1.79571733e-02, -7.93171749e-02,  1.73766345e-01,
          1.07151065e-02, -1.86400115e-01,  2.77896941e-01,
         -1.70783684e-01, -3.43858115e-02,  1.91418186e-01,
          3.14352542e-01, -9.71926656e-03, -1.94641519e-02,
         -3.15278292e-01],
        [-3.0175797

In [32]:
len(pesos0)

2

In [34]:
len(pesos0[0])

30

In [33]:
len(pesos0[1])

16

In [16]:
#realizaçõ de previsões da rede Neural e avaliação da base de teste
previsoes = rede_neural.predict(X_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step 


In [17]:
previsoes

array([[4.62737208e-24],
       [1.00000000e+00],
       [3.42166045e-10],
       [2.68780760e-18],
       [9.99189734e-01],
       [6.29668080e-23],
       [9.89940166e-01],
       [8.08116734e-01],
       [1.00000000e+00],
       [9.26711679e-01],
       [1.04073583e-23],
       [9.65108097e-01],
       [9.99324858e-01],
       [9.73984599e-01],
       [2.30396213e-09],
       [8.55945587e-17],
       [9.90395471e-02],
       [9.99921024e-01],
       [1.43022555e-06],
       [4.80964512e-01],
       [9.89131629e-01],
       [9.98262644e-01],
       [9.86787021e-01],
       [9.88214314e-01],
       [1.00000000e+00],
       [8.18679333e-02],
       [7.10789800e-01],
       [1.00000000e+00],
       [9.99976873e-01],
       [4.56398038e-06],
       [9.85974312e-01],
       [2.08275169e-02],
       [8.92331863e-14],
       [3.24525841e-04],
       [2.19132602e-24],
       [9.38839078e-01],
       [6.18000150e-01],
       [1.00000000e+00],
       [9.55722108e-02],
       [3.08763993e-05],


In [18]:
#Converter esses valores de probabilidade em True ou False. Aqui, quanto maior o valor selecionado, maior esperamos a confiança do algoritmo
previsoes = previsoes>0.5

In [19]:
previsoes

array([[False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [20]:
#Agora, precisamos comparar essas previsões com o y_teste (resultado real). O valor de resultado corresponde ao percntual de acerto da rede neural
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy_score(y_teste,previsoes)

0.8881118881118881

In [21]:
confusion_matrix(y_teste,previsoes)
#44 tumores benignos foram corretamente classificados
# 9 tumores benignos foram classificados como malignos
# 26 tumores malignos foram classificados como sendo benignos
#64 tumores malignos foram corretamente classificados

#Para calcularmos quantos registros a rede acertou, basta somar a diagonal principal
#Para calcularmos quantos registros a rede errou, basta somar a diagonal secundaria

array([[48,  4],
       [12, 79]])

In [23]:
64+44, 26 + 9

(108, 35)

In [22]:
#calculando manualmente as taxas
acuracia = 108/143
erro = 35/143
acuracia, erro

(0.7552447552447552, 0.24475524475524477)

In [29]:
rede_neural.evaluate(X_teste,y_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8907 - loss: 0.2348  


[0.2525584101676941, 0.8881118893623352]

In [ ]:
#Mais camadas ocultas são recomendadas para problemas mais complexos. è indicado testar o código variando o número de camada para ver qual dá o melhor resultado.